window_title: "Interactive phonon visualizer"
page_title: "Interactive phonon visualizer"

#custom_css_files:
# input_data:
#    - custom.css
#  process_data:
#    - custom.css

#custom_js_files:
#  input_data:
#  process_data:
#    - custom.js

about_section_title: "About the interactive phonon visualizer"

templates:
  how_to_cite: null
  about: "custom_about.html"
  select_content: "visualizer_select_structure.html"

use_upload_structure_block: False

additional_accordion_entries:
  - header: "Acknowledgements"
    template_page: ack.html

data_folder: "user_static/data/"

data:
  Bi:
    title: "Bi</sub>"
    filename: Bi.json
  BN:
    title: "BN"
    filename: BN.json
  C:
    title: "Graphene"
    filename: C.json
  PbI2:
    title: "PbI<sub>2</sub>"
    filename: PbI2.json
  MoS2-MoS2:
    title: "MoS<sub>2</sub>"
    filename: MoS2-MoS2.json
  P:
    title: "P"
    filename: P.json
  PbTe:
    title: "PbTe"
    filename: PbTe.json
  BaTiO_3:
    title: "BaTiO<sub>3</sub>"
    filename: BaTiO_3.json
